# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
