# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_cabinet', '0002_auto_20170811_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('describer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_descriptions', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_descriptions', to='image_cabinet.CabinetImage')),
            ],
        ),
    ]
