# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn --timeout 300 -b :$PORT your_image_cabinet.wsgi

beta_settings:
    cloud_sql_instances: image-cabinet:us-west1:your-image-cabinet

runtime_config:
    python_version: 3

skip_files:
- ^db.sqlite3$
- ^(.*/)?.*\.pyc$
- ^cloud_sql_proxy$
- ^(.*/)?tmp/
- ^test_images/
- ^frontend/(?!index\.html)
#- ^frontend/node_modules
# [END runtime]
